/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PublisherRole;

import Business.Adspace.Adspace;
import Business.Publisher.Publisher;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class CreateNewAdSpaceJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Publisher publisher;
    public CreateNewAdSpaceJPanel(JPanel upc, Publisher publisher) {
        initComponents();
        this.userProcessContainer = upc;
        this.publisher = publisher;
    }
    
    private Boolean adSpacevalidation() {
        if(adSpaceNameField.getText().equals("") || adSpaceSizeField.getText().equals("") || basePriceField.getText().equals("") || locationField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill in all the fields", "Empty Text", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        
        String name = adSpaceNameField.getText();
        for(int i = 0; i <name.length();i++){
        char c = name.charAt(i);  
        if((c<97 || c>122) && (c<65 || c>90)) {
         JOptionPane.showMessageDialog(null, "Adspace Name field should contain only alphabet", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        String size = adSpaceSizeField.getText();
        for(int i = 0; i <size.length();i++){
        char c = size.charAt(i);  
        if((c<48 || c>57))  {
         JOptionPane.showMessageDialog(null, "AdSize field should contain only number", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        String basePrice = basePriceField.getText();
        for(int i = 0; i <basePrice.length();i++){
        char c = basePrice.charAt(i);  
        if((c!=46 && c<48) || c>57 ) {
         JOptionPane.showMessageDialog(null, "Price field should contain only number and dot", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        String location = locationField.getText();
        for(int i = 0; i <location.length();i++){
        char c = location.charAt(i);  
         if((c<97 || c>122) && (c<65 || c>90)) {
         JOptionPane.showMessageDialog(null, "Location field should contain only alphabet", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createProductNameJLabel = new javax.swing.JLabel();
        adSpaceSizeField = new javax.swing.JTextField();
        createProductPriceJLabel = new javax.swing.JLabel();
        basePriceField = new javax.swing.JTextField();
        createAvailabilityJLabel = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        addadSpaceJButton = new javax.swing.JButton();
        createProductNameJLabel1 = new javax.swing.JLabel();
        adSpaceNameField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create New AdSpace");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 34, -1, -1));

        createProductNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createProductNameJLabel.setText("AdSpace Size:");
        add(createProductNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 154, -1, 30));

        adSpaceSizeField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adSpaceSizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adSpaceSizeFieldActionPerformed(evt);
            }
        });
        add(adSpaceSizeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 155, 210, -1));

        createProductPriceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createProductPriceJLabel.setText("Base Price:");
        add(createProductPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 221, 117, 30));

        basePriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(basePriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 221, 210, 30));

        createAvailabilityJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createAvailabilityJLabel.setText("AdLocation");
        add(createAvailabilityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 292, 116, 30));

        locationField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(locationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 292, 210, 30));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 391, 116, 32));

        addadSpaceJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addadSpaceJButton.setText("Add AdSpace");
        addadSpaceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addadSpaceJButtonActionPerformed(evt);
            }
        });
        add(addadSpaceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 391, -1, 32));

        createProductNameJLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createProductNameJLabel1.setText("AdSpace Name:");
        add(createProductNameJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 97, -1, 30));

        adSpaceNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adSpaceNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adSpaceNameFieldActionPerformed(evt);
            }
        });
        add(adSpaceNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 98, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addadSpaceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addadSpaceJButtonActionPerformed
        Boolean flag = adSpacevalidation();
        if(flag) {
            
            for (Adspace adspace : publisher.getAdspaceCatalog().getAdspaceList()) {
                if(!(adspace == null)) {
                   if(adspace.getSpaceName().equalsIgnoreCase(adSpaceNameField.getText()));
                    JOptionPane.showMessageDialog(null, "AdSpace name already exists.");
                    return;
                }
            }
            Adspace adspace = publisher.getAdspaceCatalog().addAdspace();
            String spaceName = adSpaceNameField.getText();
            int size = Integer.parseInt(adSpaceSizeField.getText());
            Float adPrice = Float.parseFloat(basePriceField.getText());
            String location = locationField.getText();
            adspace.setSpaceName(spaceName);
            adspace.setSize(size);
            adspace.setBasePrice(adPrice);
            adspace.setLocation(location);
            
            adSpaceNameField.setText("");
            adSpaceSizeField.setText("");
            basePriceField.setText("");
            locationField.setText("");
            
            JOptionPane.showMessageDialog(null, "AdSpace created successfully", "Success", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addadSpaceJButtonActionPerformed

    private void adSpaceSizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adSpaceSizeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adSpaceSizeFieldActionPerformed

    private void adSpaceNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adSpaceNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adSpaceNameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adSpaceNameField;
    private javax.swing.JTextField adSpaceSizeField;
    private javax.swing.JButton addadSpaceJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField basePriceField;
    private javax.swing.JLabel createAvailabilityJLabel;
    private javax.swing.JLabel createProductNameJLabel;
    private javax.swing.JLabel createProductNameJLabel1;
    private javax.swing.JLabel createProductPriceJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField locationField;
    // End of variables declaration//GEN-END:variables
}
