/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdvertiserRole;

import Business.Advertisement.Advertisement;
import Business.Advertiser.Advertiser;
import Business.Product.Product;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class AddAdvertisementJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Advertiser advertiser;
    String link, picture;
    
    public AddAdvertisementJPanel(JPanel upc, Advertiser advertiser) {
        initComponents();
        this.userProcessContainer = upc;
        this.advertiser = advertiser;
        populateProductCombobox();
    }
    
    private void populateProductCombobox() {
        productJComboBox.removeAllItems();
        for(Product product : advertiser.getProductCatalog().getProductList()) {
            productJComboBox.addItem(product);
        }
    }
    
    private Boolean adSpacevalidation() {
        if(adNameField.getText().equals("") || adTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fill in all the fields", "Empty Text", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        Product product = (Product) productJComboBox.getSelectedItem();
        if (product == null) {
                JOptionPane.showMessageDialog(null, "Please create a product for advertising");
                return false;
            } 
        String name = adNameField.getText();
        for(int i = 0; i <name.length();i++){
        char c = name.charAt(i);  
        if((c<97 || c>122) && (c<65 || c>90)) {
         JOptionPane.showMessageDialog(null, "Name field should contain only alphabet", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
   
        }
        }
        String text = adTextField.getText();
        for(int i = 0; i <text.length();i++){
        char c = text.charAt(i);  
        if((c<97 || c>122) && (c<65 || c>90)) {
         JOptionPane.showMessageDialog(null, "Text field should contain only alphabet", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        return true;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createProductNameJLabel = new javax.swing.JLabel();
        adNameField = new javax.swing.JTextField();
        adTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        createAdvertisementJButton = new javax.swing.JButton();
        createAvailabilityJLabel = new javax.swing.JLabel();
        productJComboBox = new javax.swing.JComboBox();
        createProductNameJLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create New Advertisement");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 36, -1, -1));

        createProductNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createProductNameJLabel.setText("AdName:");
        add(createProductNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 171, -1, 30));

        adNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adNameFieldActionPerformed(evt);
            }
        });
        add(adNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 172, 210, -1));

        adTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(adTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 220, 70));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 340, 116, 32));

        createAdvertisementJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createAdvertisementJButton.setText("Add Advertisement");
        createAdvertisementJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdvertisementJButtonActionPerformed(evt);
            }
        });
        add(createAdvertisementJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 340, -1, 32));

        createAvailabilityJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createAvailabilityJLabel.setText("AdText");
        add(createAvailabilityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 255, 116, 30));

        productJComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(productJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 92, 210, 33));

        createProductNameJLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createProductNameJLabel1.setText("Product:");
        add(createProductNameJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 90, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void adNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adNameFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createAdvertisementJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdvertisementJButtonActionPerformed
        Boolean flag = adSpacevalidation();
        if(flag) {
            Advertisement advertisement = advertiser.getAdvertisementCatalog().addAdvertisement();
            String adName = adNameField.getText();
            String adText = adTextField.getText();
            advertisement.setName(adName);
            advertisement.setAd(adText);
            Product product = (Product) productJComboBox.getSelectedItem();
            
            
            advertisement.setProduct(product);
       //     advertisement.getProduct().setProductImage(link);
          
            adNameField.setText("");
            adTextField.setText("");
            JOptionPane.showMessageDialog(null, "Advertisement created successfully", "Success", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_createAdvertisementJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adNameField;
    private javax.swing.JTextField adTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createAdvertisementJButton;
    private javax.swing.JLabel createAvailabilityJLabel;
    private javax.swing.JLabel createProductNameJLabel;
    private javax.swing.JLabel createProductNameJLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox productJComboBox;
    // End of variables declaration//GEN-END:variables
}
