/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdvertiserRole;

import Business.Advertiser.Advertiser;
import Business.Consumer.ViewHistoryList;
import Business.Enterprise.Enterprise;
import Business.Organization.PublisherOrganization;
import Business.Publisher.PublisherDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class AdvertiserWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Advertiser advertiser;
    UserAccount userAccount;
    PublisherDirectory publisherDirectory;
    Enterprise enterprise;
    ViewHistoryList viewHistoryList;
    PublisherOrganization publisherOrganization;
    
    public AdvertiserWorkAreaJPanel(JPanel upc, Advertiser advertiser, UserAccount userAccount, PublisherDirectory publisherDirectory, Enterprise enterprise, ViewHistoryList viewHistoryList, PublisherOrganization publisherOrganization) {
        initComponents();
        this.userProcessContainer = upc;
        this.advertiser = advertiser;
        this.userAccount = userAccount;
        this.publisherDirectory = publisherDirectory;
        this.enterprise = enterprise;
        this.viewHistoryList = viewHistoryList;
        this.publisherOrganization = publisherOrganization;
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageadvertisementJButton = new javax.swing.JButton();
        productManagerJLabel = new javax.swing.JLabel();
        manageProductJButton = new javax.swing.JButton();
        adExchangeJButton = new javax.swing.JButton();
        topBidderJButton = new javax.swing.JButton();
        productViewHistoryJButton = new javax.swing.JButton();

        manageadvertisementJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageadvertisementJButton.setText("Manage Advertisement Catalog >>");
        manageadvertisementJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageadvertisementJButtonActionPerformed(evt);
            }
        });

        productManagerJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        productManagerJLabel.setText("Advertiser Work Area");

        manageProductJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageProductJButton.setText("Manage Products >>");
        manageProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductJButtonActionPerformed(evt);
            }
        });

        adExchangeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adExchangeJButton.setText("Advertisement Exchange >>");
        adExchangeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adExchangeJButtonActionPerformed(evt);
            }
        });

        topBidderJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topBidderJButton.setText("View Top Bidders for a space >>");
        topBidderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topBidderJButtonActionPerformed(evt);
            }
        });

        productViewHistoryJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productViewHistoryJButton.setText("View History Of Products >>");
        productViewHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productViewHistoryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productManagerJLabel)
                    .addComponent(productViewHistoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageProductJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageadvertisementJButton)
                    .addComponent(adExchangeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topBidderJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(productManagerJLabel)
                .addGap(44, 44, 44)
                .addComponent(productViewHistoryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(manageProductJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(manageadvertisementJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(adExchangeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(topBidderJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageadvertisementJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageadvertisementJButtonActionPerformed
        ManageAdvertisementJPanel mavjp = new ManageAdvertisementJPanel(userProcessContainer, advertiser);
        userProcessContainer.add("ManageAdvCatalogJPanel",mavjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageadvertisementJButtonActionPerformed

    private void manageProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductJButtonActionPerformed
        ManageProductJPanel mprjp = new ManageProductJPanel(userProcessContainer, advertiser);
        userProcessContainer.add("ManageProductJPanel",mprjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductJButtonActionPerformed

    private void adExchangeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adExchangeJButtonActionPerformed

        if (publisherDirectory ==null) {
                  
                   JOptionPane.showMessageDialog(null, "Please create publisherorganization/publisher before proceeding");
             
               } else {
        AdvertisementExchangeJPanel aejp = new AdvertisementExchangeJPanel(userProcessContainer, publisherDirectory, advertiser, userAccount, enterprise, publisherOrganization);
        userProcessContainer.add("AdvertisementExchangeJPanel",aejp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_adExchangeJButtonActionPerformed

    private void topBidderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topBidderJButtonActionPerformed
        ViewTopBidsJPanel vtjp = new ViewTopBidsJPanel(userProcessContainer,publisherOrganization);
        userProcessContainer.add("ViewTopBidderJPanel",vtjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_topBidderJButtonActionPerformed

    private void productViewHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productViewHistoryJButtonActionPerformed
        ProductHistoryJPanel phjp = new ProductHistoryJPanel(userProcessContainer,viewHistoryList,userAccount);
        userProcessContainer.add("ProductHistoryJPanel",phjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_productViewHistoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adExchangeJButton;
    private javax.swing.JButton manageProductJButton;
    private javax.swing.JButton manageadvertisementJButton;
    private javax.swing.JLabel productManagerJLabel;
    private javax.swing.JButton productViewHistoryJButton;
    private javax.swing.JButton topBidderJButton;
    // End of variables declaration//GEN-END:variables
}
