/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdvertiserRole;

import Business.Consumer.ViewHistory;
import Business.Consumer.ViewHistoryList;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Sriram
 */
public class ProductHistoryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ViewHistoryList viewHistoryList;
    ViewHistory vh;
    UserAccount userAccount;
    
    public ProductHistoryJPanel(JPanel upc, ViewHistoryList viewHistoryList, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.viewHistoryList = viewHistoryList;
        this.userAccount = userAccount;
        populateViewHistory();
        
        balanceJTextField.setText(String.valueOf(userAccount.getFinanceDetail().getBalance()));
    }
    
    private void populateViewHistory() {
        
        DefaultTableModel dtm = (DefaultTableModel) productHistoryJTable.getModel();
        dtm.setRowCount(0);
        
        for(ViewHistory viewHistory : viewHistoryList.getViewHistoryDirectory()) {
            Object row[] = new Object[2];
            row[0] = viewHistory;
            row[1] = viewHistory.getCount();
            dtm.addRow(row);
        }
    }
    
    private void populateMaxViewedProduct() {
        
        int maxVal = 0;
        for(ViewHistory viewHistory : viewHistoryList.getViewHistoryDirectory()) {
            if(viewHistory.getCount() > maxVal) {
                maxVal = viewHistory.getCount();
                vh = viewHistory;
                topviewedJTextField.setText(vh.getProduct().getProductName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productHistoryJTable = new javax.swing.JTable();
        topViewedJButton = new javax.swing.JButton();
        topviewedJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        viewPerformanceJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        balanceJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productHistoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productHistoryJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 376, 94));

        topViewedJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        topViewedJButton.setText("Top Viewed Product");
        topViewedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topViewedJButtonActionPerformed(evt);
            }
        });
        add(topViewedJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 233, -1, -1));

        topviewedJTextField.setEditable(false);
        topviewedJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(topviewedJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 233, 120, 31));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 339, 110, 33));

        viewPerformanceJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewPerformanceJButton.setText("View Performance >>");
        viewPerformanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerformanceJButtonActionPerformed(evt);
            }
        });
        add(viewPerformanceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 335, 210, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VIEWHISTORY OF PRODUCT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Advertiser Current Balance:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 220, 30));

        balanceJTextField.setEditable(false);
        add(balanceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void topViewedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topViewedJButtonActionPerformed
         populateMaxViewedProduct();
    }//GEN-LAST:event_topViewedJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewPerformanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerformanceJButtonActionPerformed
      /*  DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(int i=0;i<productHistoryJTable.getRowCount();i++) {
                ViewHistory viewHistory = (ViewHistory)productHistoryJTable.getValueAt(i, 0);  
                String prodName = viewHistory.getProduct().getProductName();
         
               dataset.setValue((Number) productHistoryJTable.getValueAt(i, 1), "Count", prodName);
                JFreeChart chart = ChartFactory.createBarChart("ViewPerformance", "ProductName", "Count", dataset, PlotOrientation.VERTICAL, false, true, false);
                CategoryPlot p = chart.getCategoryPlot();
                p.setRangeGridlinePaint(Color.black);
                ChartFrame frame = new ChartFrame("BarChart for Product",chart); 
                frame.setVisible(true);
                frame.setSize(500,350); */
        ProductHistoryPerformanceJPanel phpj = new ProductHistoryPerformanceJPanel(userProcessContainer,viewHistoryList);
        userProcessContainer.add("ProductHistoryPerformance",phpj);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
  
                     
    }//GEN-LAST:event_viewPerformanceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField balanceJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productHistoryJTable;
    private javax.swing.JButton topViewedJButton;
    private javax.swing.JTextField topviewedJTextField;
    private javax.swing.JButton viewPerformanceJButton;
    // End of variables declaration//GEN-END:variables
}
