/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ConsumerRole;

import Business.Consumer.Consumer;
import Business.Order.MasterOrderCatalog;
import Business.Order.Order;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdExchangeRequest;
import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class PurchaseProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseProductJPanel
     */
    JPanel userProcessContainer;
    MasterOrderCatalog masterOrderCatalog;
    AdExchangeRequest aer;
    Order order;
    UserAccount userAccount;
    Consumer consumer;
    private Boolean isCheckedOut = false;
    
    public PurchaseProductJPanel(JPanel upc, MasterOrderCatalog moc, AdExchangeRequest aer, UserAccount userAccount, Consumer consumer) throws IOException{
        initComponents();
        this.userProcessContainer = upc;
        this.masterOrderCatalog = moc;
        this.aer = aer;
        this.userAccount = userAccount;
        this.consumer = consumer;
        populateAdvProduct();
        
    }
    
    private void populateAdvProduct() throws IOException {
        productNameField.setText(aer.getAdvertisement().getProduct().getProductName());
        idField.setText(String.valueOf(aer.getAdvertisement().getProduct().getModelNumber()));
        productPriceField.setText(String.valueOf(aer.getAdvertisement().getProduct().getPrice()));
        availabilityJTextField.setText(String.valueOf(aer.getAdvertisement().getProduct().getAvailability()));
        textJLabel.setText(aer.getAdvertisement().getAd());
        Product product = aer.getAdvertisement().getProduct();
        String fileLoc = product.getProductImage();
        File file = new File(fileLoc);
   //     Image image = new ImageIcon(product.getProductImage()).getImage();
        BufferedImage bi = product.scaleImage(ImageIO.read(file), 177, 177);
//     ImageIcon icon = new ImageIcon(product.scaleImage(image, 177, 150));
        imageJLabel.setIcon(new ImageIcon(bi));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prodNameJLabel = new javax.swing.JLabel();
        productNameField = new javax.swing.JTextField();
        prodIdJLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        prodPriceJLabel = new javax.swing.JLabel();
        productPriceField = new javax.swing.JTextField();
        availabilityJLabel = new javax.swing.JLabel();
        availabilityJTextField = new javax.swing.JTextField();
        quantityJSpinner = new javax.swing.JSpinner();
        addCartJButton = new javax.swing.JButton();
        makePaymentJButton = new javax.swing.JButton();
        imageJLabel = new javax.swing.JLabel();
        viewProductDetailJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        textJLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prodNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prodNameJLabel.setText("Product Name:");
        add(prodNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 30));

        productNameField.setEditable(false);
        productNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameFieldActionPerformed(evt);
            }
        });
        add(productNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 210, -1));

        prodIdJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prodIdJLabel.setText("Product ID:");
        add(prodIdJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 117, 30));

        idField.setEditable(false);
        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 210, -1));

        prodPriceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prodPriceJLabel.setText("Product Price:");
        add(prodPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 117, 30));

        productPriceField.setEditable(false);
        productPriceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(productPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 208, 30));

        availabilityJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        availabilityJLabel.setText("Availability:");
        add(availabilityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 120, 30));

        availabilityJTextField.setEditable(false);
        availabilityJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(availabilityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 208, 30));
        add(quantityJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 73, -1));

        addCartJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addCartJButton.setText("ADD TO CART");
        addCartJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCartJButtonActionPerformed(evt);
            }
        });
        add(addCartJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, -1, -1));

        makePaymentJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        makePaymentJButton.setText("Make Payment >>");
        makePaymentJButton.setEnabled(false);
        makePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePaymentJButtonActionPerformed(evt);
            }
        });
        add(makePaymentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, -1, -1));
        add(imageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 400, 280));

        viewProductDetailJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewProductDetailJLabel.setText("PURCHASE PRODUCT PANEL");
        add(viewProductDetailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, -1, -1));

        textJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(textJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 154, 400, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void productNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameFieldActionPerformed

    private void addCartJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCartJButtonActionPerformed
        
    
        int quantity = (Integer) quantityJSpinner.getValue();
        if ((quantity <= 0) || (quantity > aer.getAdvertisement().getProduct().getAvailability()) )
        {
            JOptionPane.showMessageDialog(null,"Invalid quantity. Please enter a valid quantity");
            return;
        }
            
            String advName = String.valueOf(aer.getAdvertisement().getName());
            order = new Order();
            order.addAdvOrderItem(aer.getAdvertisement().getProduct(), aer.getAdvertisement().getProduct().getAvailability()-quantity, advName, userAccount.getConsumer().getFirstName());
            availabilityJTextField.setText(String.valueOf(aer.getAdvertisement().getProduct().getAvailability() - quantity));
            aer.getAdvertisement().getProduct().setPurchasedQuantity(aer.getAdvertisement().getProduct().getAvailability() - (aer.getAdvertisement().getProduct().getAvailability() - quantity));
            System.out.println("The val f purQuantity is " + aer.getAdvertisement().getProduct().getPurchasedQuantity());
            aer.getAdvertisement().getProduct().setAvailability(aer.getAdvertisement().getProduct().getAvailability() - quantity);
            
            makePaymentJButton.setEnabled(true);
            
            JOptionPane.showMessageDialog(null,"The product has been added to cart");
            
    }//GEN-LAST:event_addCartJButtonActionPerformed

    private void makePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePaymentJButtonActionPerformed
        
        ManagePaymentJPanel mpjp = new ManagePaymentJPanel(userProcessContainer, aer, userAccount, order, masterOrderCatalog, consumer);
        userProcessContainer.add("ManagePayment", mpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        makePaymentJButton.setEnabled(false);
    }//GEN-LAST:event_makePaymentJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCartJButton;
    private javax.swing.JLabel availabilityJLabel;
    private javax.swing.JTextField availabilityJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JButton makePaymentJButton;
    private javax.swing.JLabel prodIdJLabel;
    private javax.swing.JLabel prodNameJLabel;
    private javax.swing.JLabel prodPriceJLabel;
    private javax.swing.JTextField productNameField;
    private javax.swing.JTextField productPriceField;
    private javax.swing.JSpinner quantityJSpinner;
    private javax.swing.JLabel textJLabel;
    private javax.swing.JLabel viewProductDetailJLabel;
    // End of variables declaration//GEN-END:variables
}
