/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ConsumerRole;

import Business.Order.OrderItem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class ViewOrderItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrderItemJPanel
     */
    JPanel userProcessContainer;
    OrderItem orderItem;
    public ViewOrderItemJPanel(JPanel upc, OrderItem orderItem) {
        initComponents();
        this.userProcessContainer=upc;
        this.orderItem=orderItem;
        populateFields(orderItem);
    }
    private void populateFields(OrderItem orderItem){
        nameJTextField.setText(orderItem.getProduct().getProductName());
        quantityJTextField.setText(String.valueOf(orderItem.getQuantity()));
        priceJTextField.setText(String.valueOf(orderItem.getQuantity() * orderItem.getProduct().getPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        productNameJLabel = new javax.swing.JLabel();
        productQuanJLabel = new javax.swing.JLabel();
        totalPriceJLabel = new javax.swing.JLabel();
        priceJTextField = new javax.swing.JTextField();
        quantityJTextField = new javax.swing.JTextField();
        nameJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VIEW ORDER ITEM");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 36, 240, 35));

        productNameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productNameJLabel.setText("ProductName:");
        add(productNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 30));

        productQuanJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productQuanJLabel.setText("ProductQuantity:");
        add(productQuanJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 172, 140, 27));

        totalPriceJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalPriceJLabel.setText("TotalPrice:");
        add(totalPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 226, 140, 30));

        priceJTextField.setEditable(false);
        priceJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceJTextFieldActionPerformed(evt);
            }
        });
        add(priceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 227, 210, -1));

        quantityJTextField.setEditable(false);
        quantityJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityJTextFieldActionPerformed(evt);
            }
        });
        add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 171, 210, -1));

        nameJTextField.setEditable(false);
        nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 122, 210, -1));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 114, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void priceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceJTextFieldActionPerformed

    private void quantityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityJTextFieldActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JLabel productNameJLabel;
    private javax.swing.JLabel productQuanJLabel;
    private javax.swing.JTextField quantityJTextField;
    private javax.swing.JLabel totalPriceJLabel;
    // End of variables declaration//GEN-END:variables
}
