/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.Order.MasterOrderCatalog;
import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Supplier supplier;
    MasterOrderCatalog masterOrderCatalog;
    UserAccount userAccount;
    public SupplierWorkAreaJPanel(JPanel upc, Supplier supplier, MasterOrderCatalog masterOrderCatalog, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=upc;
        this.supplier=supplier;
        this.masterOrderCatalog=masterOrderCatalog;
        this.userAccount=userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productManagerJLabel = new javax.swing.JLabel();
        manageProductJButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productManagerJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        productManagerJLabel.setText("SUPPLIER WORK AREA");
        add(productManagerJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        manageProductJButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageProductJButton1.setText("Manage Product Catalog >>");
        manageProductJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductJButton1ActionPerformed(evt);
            }
        });
        add(manageProductJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void manageProductJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductJButton1ActionPerformed
        ManageProductCatalogJPanel mpjp = new ManageProductCatalogJPanel(userProcessContainer, supplier);
        userProcessContainer.add("ManageProductCatalogJPanel",mpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageProductJButton1;
    private javax.swing.JLabel productManagerJLabel;
    // End of variables declaration//GEN-END:variables
}
