/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Advertiser.Advertiser;
import Business.Advertiser.AdvertiserDirectory;
import Business.Organization.AdvertiserOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class AddAdvertiserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddAdvertiserJPanel
     */
    JPanel userProcessContainer;
    AdvertiserOrganization advertiserOrganization;
    AdvertiserDirectory advertiserDirectory;
    
    public AddAdvertiserJPanel(JPanel upc, AdvertiserOrganization advertiserOrganization, AdvertiserDirectory advertiserDirectory) {
        initComponents();
        this.userProcessContainer = upc;
        this.advertiserOrganization = advertiserOrganization;
        this.advertiserDirectory = advertiserDirectory;
    }
    
    private Boolean advertiservalidation() {
        if(nameJTextfield.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Fill in advertiser the field. It should not be empty", "Empty Text", JOptionPane.WARNING_MESSAGE);
         return false;   
        }
        String advName = nameJTextfield.getText();
        for(int i = 0; i <advName.length();i++){
        char c = advName.charAt(i);  
        if((c<97 || c>122) && (c<65 || c>90)) {
         JOptionPane.showMessageDialog(null, "Advertiser Name field should contain only alphabet", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameJTextfield = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        addAdvertiserJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("NEW ADVERTISER");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 27, 230, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 100, 30));

        nameJTextfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nameJTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 160, 30));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 303, 110, 30));

        addAdvertiserJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addAdvertiserJButton.setText("Add Advertiser >>");
        addAdvertiserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdvertiserJButtonActionPerformed(evt);
            }
        });
        add(addAdvertiserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addAdvertiserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdvertiserJButtonActionPerformed
        Boolean flag = advertiservalidation();
        if(flag) {
            if(advertiserOrganization ==null) {
                JOptionPane.showMessageDialog(null, "Please assign organization to Advertiser before creating");
                return;
            }
            String advertiserName = nameJTextfield.getText();
            Advertiser advertiser = advertiserDirectory.addAdvertiser();
            advertiser.setFirstName(advertiserName);
            nameJTextfield.setText("");
            JOptionPane.showMessageDialog(null, "Advertiser created successfully", "Success", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_addAdvertiserJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdvertiserJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameJTextfield;
    // End of variables declaration//GEN-END:variables
}
