/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Organization.PublisherOrganization;
import Business.Publisher.Publisher;
import Business.Publisher.PublisherDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class AddPublisherJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPublisherJPanel
     */
    JPanel userProcessContainer;
    PublisherOrganization publisherOrganization;
    PublisherDirectory publisherDirectory;
    public AddPublisherJPanel(JPanel upc, PublisherOrganization publisherOrganization, PublisherDirectory publisherDirectory) {
        initComponents(); 
        this.userProcessContainer = upc;
        this.publisherOrganization = publisherOrganization;
        this.publisherDirectory = publisherDirectory;
    }
    
    private Boolean publishervalidation() {
        if(nameJTextfield.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Fill in publisher field. It should not be empty", "Empty Text", JOptionPane.WARNING_MESSAGE);
         return false;   
        }
        String pubName = nameJTextfield.getText();
        for(int i = 0; i <pubName.length();i++){
        char c = pubName.charAt(i);  
        if((c<97 || c>122) && (c<65 || c>90)) {
         JOptionPane.showMessageDialog(null, "Publisher Name field should contain only alphabet", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameJTextfield = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        publisherJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("NEW PUBLISHER");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 230, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 80, 30));

        nameJTextfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nameJTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 180, 30));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 110, 30));

        publisherJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        publisherJButton.setText("Add Publisher >>");
        publisherJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherJButtonActionPerformed(evt);
            }
        });
        add(publisherJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void publisherJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherJButtonActionPerformed
        Boolean flag = publishervalidation();
        if(flag) {
            if(publisherOrganization ==null) {
                JOptionPane.showMessageDialog(null, "Please assign organization to publisher before creating");
                return;
            }
        String publisherName = nameJTextfield.getText();
        Publisher publisher = publisherDirectory.addPublisher();
        publisher.setFirstName(publisherName);
        nameJTextfield.setText("");
        
        JOptionPane.showMessageDialog(null, "Publisher created successfully", "Success", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_publisherJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameJTextfield;
    private javax.swing.JButton publisherJButton;
    // End of variables declaration//GEN-END:variables
}
