/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Organization.SupplierOrganization;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class AddSupplier extends javax.swing.JPanel {

    JPanel userProcessContainer;
    SupplierOrganization supplierOrganization;
    SupplierDirectory supplierDirectory;
    
    public AddSupplier(JPanel upc, SupplierOrganization supplierOrganization, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer=upc;
        this.supplierOrganization=supplierOrganization;
        this.supplierDirectory=supplierDirectory;
    }
    
    private Boolean validation() {
        if(namejTextField.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Fill in the supplier field. It should not be empty", "Empty Text", JOptionPane.WARNING_MESSAGE);
         return false;   
        }
        String supName = namejTextField.getText();
        for(int i = 0; i <supName.length();i++){
        char c = supName.charAt(i);  
        if((c<97 || c>122) && (c<65 || c>90)) {
         JOptionPane.showMessageDialog(null, "Supplier Name field should contain only alphabet", "Mismatch", JOptionPane.WARNING_MESSAGE);
         return false;
        }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        addJButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("NEW SUPPLIER");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 190, 30));

        namejTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 180, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 80, 30));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<<BACK");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 110, 30));

        addJButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addJButton1.setText("ADD SUPPLIER >>");
        addJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButton1ActionPerformed(evt);
            }
        });
        add(addJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButton1ActionPerformed
        Boolean flag = validation();
        if(flag) {
            if(supplierOrganization ==null) {
                JOptionPane.showMessageDialog(null, "Please assign organization to suplier before creating");
                return;
            }
        String supplierName = namejTextField.getText();
        Supplier supplier = supplierDirectory.addSupplier();
        supplier.setFirstName(supplierName);
        namejTextField.setText("");
        
        JOptionPane.showMessageDialog(null, "Supplier created successfully", "Success", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton1;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField namejTextField;
    // End of variables declaration//GEN-END:variables
}
