/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Advertiser.AdvertiserDirectory;
import Business.Consumer.ConsumerDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AdvertiserOrganization;
import Business.Organization.Organization;
import Business.Organization.PublisherOrganization;
import Business.Organization.SupplierOrganization;
import Business.Publisher.PublisherDirectory;
import Business.Supplier.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Sriram
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    
    JPanel userProcessContainer;
    Enterprise enterprise;
    SupplierDirectory supplierDirectory;
    ConsumerDirectory consumerDirectory;
    PublisherDirectory publisherDirectory;
    AdvertiserDirectory advertiserDirectory;
    EcoSystem system;
   
    
    public AdminWorkAreaJPanel(JPanel upc, Enterprise enterprise, ConsumerDirectory consumerDirectory, EcoSystem system) {
        initComponents();
        this.userProcessContainer=upc;
        this.enterprise=enterprise;
        this.consumerDirectory = consumerDirectory;
        this.system = system;
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrganizationJButton = new javax.swing.JButton();
        managesupplierJButton = new javax.swing.JButton();
        manageConsumersJButton = new javax.swing.JButton();
        managePublisherJButton = new javax.swing.JButton();
        manageUserAccountJButton = new javax.swing.JButton();
        manageAdvertiserJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ADMIN WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        manageOrganizationJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageOrganizationJButton.setText("Manage Organization >>");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 72, 260, -1));

        managesupplierJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        managesupplierJButton.setText("Manage Suppliers >>");
        managesupplierJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managesupplierJButtonActionPerformed(evt);
            }
        });
        add(managesupplierJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 145, 260, 33));

        manageConsumersJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageConsumersJButton.setText("Manage Consumers >>");
        manageConsumersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageConsumersJButtonActionPerformed(evt);
            }
        });
        add(manageConsumersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 214, 260, -1));

        managePublisherJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        managePublisherJButton.setText("Manage Publishers >>");
        managePublisherJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePublisherJButtonActionPerformed(evt);
            }
        });
        add(managePublisherJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 287, 260, -1));

        manageUserAccountJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageUserAccountJButton.setText("Manage UserAccount >>");
        manageUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountJButtonActionPerformed(evt);
            }
        });
        add(manageUserAccountJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 260, -1));

        manageAdvertiserJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageAdvertiserJButton.setText("Manage Advertisers >>");
        manageAdvertiserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdvertiserJButtonActionPerformed(evt);
            }
        });
        add(manageAdvertiserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 352, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        ManageOrganizationJPanel mojp = new ManageOrganizationJPanel(userProcessContainer,enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageOrganizationJPanel",mojp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
       
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void managesupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managesupplierJButtonActionPerformed
        SupplierOrganization supplierOrganization = null;
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if(org.getName().equals(Organization.Type.Supplier.getValue())) {
                
                supplierOrganization = (SupplierOrganization) org;
                supplierDirectory = supplierOrganization.getSupplierDirectory();
                
            }
        }
            
        ManageSuppliersJPanel ms = new ManageSuppliersJPanel(userProcessContainer, supplierOrganization, supplierDirectory);
        userProcessContainer.add("ManageSuppliers",ms);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_managesupplierJButtonActionPerformed

    private void manageConsumersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageConsumersJButtonActionPerformed
        
        
        ManageConsumerJPanel mcjp = new ManageConsumerJPanel(userProcessContainer,consumerDirectory);
        userProcessContainer.add("ManageConsumers",mcjp);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageConsumersJButtonActionPerformed

    private void managePublisherJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePublisherJButtonActionPerformed
       
         PublisherOrganization publisherOrganization = null;
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if(org.getName().equals(Organization.Type.Publisher.getValue())) {
                
                publisherOrganization = (PublisherOrganization) org;
                publisherDirectory = publisherOrganization.getPublisherDirectory();
                
            }
        }
        ManagePublisherJPanel mpjp = new ManagePublisherJPanel(userProcessContainer,publisherOrganization,publisherDirectory);
        userProcessContainer.add("ManagePublisherJPanel",mpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePublisherJButtonActionPerformed

    private void manageAdvertiserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdvertiserJButtonActionPerformed
        AdvertiserOrganization advertiserOrganization = null;
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if(org.getName().equals(Organization.Type.Advertiser.getValue())) {
                
                advertiserOrganization = (AdvertiserOrganization) org;
                advertiserDirectory = advertiserOrganization.getAdvertiserDirectory();
                
            }
        }
        
        ManageAdvertiserJPanel majp = new ManageAdvertiserJPanel(userProcessContainer,advertiserOrganization,advertiserDirectory);
        userProcessContainer.add("ManageAdvertiser",majp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdvertiserJButtonActionPerformed

    private void manageUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountJButtonActionPerformed
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if(org.getName().equals(Organization.Type.Supplier.getValue())) {
                
                SupplierOrganization supplierOrganization = (SupplierOrganization) org;
                supplierDirectory = supplierOrganization.getSupplierDirectory();
                
            }
        }
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if(org.getName().equals(Organization.Type.Publisher.getValue())) {
                
                PublisherOrganization publisherOrganization = (PublisherOrganization) org;
                publisherDirectory = publisherOrganization.getPublisherDirectory();
                
            }
        }
        
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if(org.getName().equals(Organization.Type.Advertiser.getValue())) {
                
                AdvertiserOrganization advertiserOrganization = (AdvertiserOrganization) org;
                advertiserDirectory = advertiserOrganization.getAdvertiserDirectory();
                
            }
        }
        
        ManageUserAccountJPanel mujp = new ManageUserAccountJPanel(userProcessContainer,enterprise,supplierDirectory,publisherDirectory,advertiserDirectory,system);
        userProcessContainer.add("ManageUserAcount",mujp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageUserAccountJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageAdvertiserJButton;
    private javax.swing.JButton manageConsumersJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton managePublisherJButton;
    private javax.swing.JButton manageUserAccountJButton;
    private javax.swing.JButton managesupplierJButton;
    // End of variables declaration//GEN-END:variables
}
