/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Organization.SupplierOrganization;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sriram
 */
public class ManageSuppliersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel userProcessContainer;
    SupplierOrganization supplierOrganization;
    SupplierDirectory supplierDirectory;
    public ManageSuppliersJPanel(JPanel upc, SupplierOrganization supplierOrganization, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer = upc;
        this.supplierOrganization = supplierOrganization;
        this.supplierDirectory = supplierDirectory;
        
    }
    
    private void populateSupplierTable() {
        DefaultTableModel dtm = (DefaultTableModel)supplierJTable.getModel();
        dtm.setRowCount(0);
        
        for (Supplier supplier : supplierDirectory.getSupplierList()) {
            Object row[] = new Object[1];
            row[0] = supplier;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        supplierJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        addSupplierJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(supplierJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 360, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE SUPPLIERS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        refreshJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, 30));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 110, 30));

        removeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeJButton.setText("Remove >>");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, 30));

        addSupplierJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addSupplierJButton.setText("AddSuppliers >>");
        addSupplierJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierJButtonActionPerformed(evt);
            }
        });
        add(addSupplierJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        if (supplierDirectory!=null) {
        populateSupplierTable();
        }
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        int selectedRow = supplierJTable.getSelectedRow();
        if(selectedRow>=0){
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete", "Warning", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION){
                Supplier supplier = (Supplier)supplierJTable.getValueAt(selectedRow,0);
                supplierDirectory.deleteSupplier(supplier);
                populateSupplierTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Please select a publisher to delete");
        }
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void addSupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierJButtonActionPerformed
        AddSupplier as = new AddSupplier(userProcessContainer,supplierOrganization,supplierDirectory);
        userProcessContainer.add("AddSupplier",as);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addSupplierJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupplierJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton removeJButton;
    private javax.swing.JTable supplierJTable;
    // End of variables declaration//GEN-END:variables
}
