/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sriram
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory;
    
    public ManageOrganizationJPanel(JPanel upc, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer=upc;
        this.organizationDirectory=organizationDirectory;
        populateCombobox();
        populateTable();
    }
    
    private void populateCombobox() {
        orgJComboBox.removeAllItems();
        for(Type type : Organization.Type.values()) {
        
        if ((!type.getValue().equals(Type.Admin.getValue())) && (!type.getValue().equals(Type.Consumer.getValue()))){
            orgJComboBox.addItem(type);
        }
        }
    }
    private void populateTable() {
        
        DefaultTableModel dtm = (DefaultTableModel)organizationJTable.getModel();
        dtm.setRowCount(0);
        
        for(Organization organization : organizationDirectory.getOrganizationList()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        orgJComboBox = new javax.swing.JComboBox();
        backJButton = new javax.swing.JButton();
        createOrganizationJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        deleteOrgJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrgID", "OrgName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);
        if (organizationJTable.getColumnModel().getColumnCount() > 0) {
            organizationJTable.getColumnModel().getColumn(0).setResizable(false);
            organizationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 367, 89));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("OrganizationType");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, 25));

        orgJComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(orgJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 127, 25));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 120, 32));

        createOrganizationJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createOrganizationJButton.setText("CreateOrganization >>");
        createOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrganizationJButtonActionPerformed(evt);
            }
        });
        add(createOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 230, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MANAGE ORGANIZATION");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        deleteOrgJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteOrgJButton.setText("Delete Organization >>");
        deleteOrgJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrgJButtonActionPerformed(evt);
            }
        });
        add(deleteOrgJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 453, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void createOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrganizationJButtonActionPerformed
       Type type = (Type)orgJComboBox.getSelectedItem();
       for(Organization org : organizationDirectory.getOrganizationList()) {
           if(type.getValue().equals(org.getName())) {
               
               JOptionPane.showMessageDialog(null, "Organization already exists");
               return; 
           }
       }
       organizationDirectory.createOrganization(type);
       populateTable();
    }//GEN-LAST:event_createOrganizationJButtonActionPerformed

    private void deleteOrgJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrgJButtonActionPerformed
        int selectedRow = organizationJTable.getSelectedRow();
        if(selectedRow>=0){
            Organization org  =(Organization)organizationJTable.getValueAt(selectedRow,1);
                if (org.getName().equals("Admin Organization")) {
                    JOptionPane.showMessageDialog(null, "You do not have an access to delete Admin Organization");
                    return;
                }
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete", "Warning", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                
                organizationDirectory.deleteOrganization(org);
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Please select an Organization to delete");
        }
    }//GEN-LAST:event_deleteOrgJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createOrganizationJButton;
    private javax.swing.JButton deleteOrgJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox orgJComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
