/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Advertiser.Advertiser;
import Business.Advertiser.AdvertiserDirectory;
import Business.Organization.AdvertiserOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sriram
 */
public class ManageAdvertiserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdvertiserJPanel
     */
    JPanel userProcessContainer;
    AdvertiserOrganization advertiserOrganization;
    AdvertiserDirectory advertiserDirectory;
    public ManageAdvertiserJPanel(JPanel upc, AdvertiserOrganization advertiserOrganization, AdvertiserDirectory advertiserDirectory) {
        initComponents();
        this.userProcessContainer = upc;
        this.advertiserOrganization = advertiserOrganization;
        this.advertiserDirectory = advertiserDirectory;
        
    }
    
    private void populateAdvertiserTable() {
        DefaultTableModel dtm = (DefaultTableModel)advertiserJTable.getModel();
        dtm.setRowCount(0);
        
        for (Advertiser advertiser : advertiserDirectory.getAdvertiserList()) {
            Object row[] = new Object[1];
            row[0] = advertiser;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        advertiserJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        addAdvertiserJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 113, 100, 30));

        advertiserJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Advertiser Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(advertiserJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 390, 120));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 110, 30));

        removeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeJButton.setText("Remove >>");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 333, 130, 30));

        addAdvertiserJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addAdvertiserJButton.setText("Add Advertiser >>");
        addAdvertiserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdvertiserJButtonActionPerformed(evt);
            }
        });
        add(addAdvertiserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 180, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE ADVERTISERS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        if(advertiserDirectory!=null) {
        populateAdvertiserTable();
        }
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        int selectedRow = advertiserJTable.getSelectedRow();
        if(selectedRow>=0){
            int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete", "Warning", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION){
                Advertiser advertiser = (Advertiser)advertiserJTable.getValueAt(selectedRow,0);
                advertiserDirectory.deleteAdvertiser(advertiser);
                populateAdvertiserTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Please select an Advertiser to delete");
        }
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void addAdvertiserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdvertiserJButtonActionPerformed
        AddAdvertiserJPanel aa = new AddAdvertiserJPanel(userProcessContainer,advertiserOrganization,advertiserDirectory);
        userProcessContainer.add("AddAdvertiser",aa);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_addAdvertiserJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdvertiserJButton;
    private javax.swing.JTable advertiserJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton removeJButton;
    // End of variables declaration//GEN-END:variables
}
