/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.WorkQueue.SignUpRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sriram
 */
public class ViewSignUpStatusJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccountDirectory userAccountDirectory;
    
    public ViewSignUpStatusJPanel(JPanel upc, UserAccountDirectory ua) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccountDirectory = ua;
        populateSignUpStatus();
    }
    
    private void populateSignUpStatus() {
        
        DefaultTableModel dtm = (DefaultTableModel) viewSignUpStatusJTable.getModel();
        dtm.setRowCount(0);
        
        for (UserAccount userAccount : userAccountDirectory.getUserAccountList()) {
            if(userAccount.getUserName().equals("sysadmin")) {
                for (WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()) {
                  SignUpRequest consReq = (SignUpRequest) wr;
                  Object row[] = new Object[4];
            row[0] = wr.getMessage();
            row[1] = consReq.getFirstName();
            row[2] = consReq.getLastName();
            row[3] = consReq.getSignUpResult();
            dtm.addRow(row);
                }
            }
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewSignUpStatusJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewSignUpStatusJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "First Name", "Last Name", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewSignUpStatusJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 144, 401, 131));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("VIEW SIGNUP STATUS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 210, 25));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewSignUpStatusJTable;
    // End of variables declaration//GEN-END:variables
}
